languageCode = "en"
languageName = "English"
weight = 1
title = "BinaryDigit's Cafe"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "Jan 2 2006"
logo = "images/michigan-flation.png"
secondaryLogo = "images/statue-of-liberty-flaticon.png"
description = "A random collection of notes and articles."
copyright = '<script src="https://status.lol/binarydigit.js?time&link&fluent"></script>'

[author]
name = "BinaryDigit"
image = "images/AC-Profile-Photo.png"
headline = "My digital home for hobbies and notes"
bio = "My digital home for hobbies and notes"
links = [
    { notebook = "https://notes.binarydigit.cafe/" },
    { clock = "https://now.binarydigit.cafe"},
    { link = "https://links.binarydigit.cafe"},
    { mastodon = "https://social.lol/@BinaryDigit/" },
    { twitch = "https://twitch.tv/binarydigit"},
    { github = "https://github.com/BinaryDigitCode"},
    { mail-forward = "https://letterbird.co/binarydigit"}
]
