[build.environment]
HUGO_VERSION = "0.126.0"
TZ = "America/New_York"

[build]
publish = "public"
command = "hugo --gc --minify"

[[redirects]]
  from = "/feed.xml"
  to = "/posts/index.xml"
  status = 301